---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: devdb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: postgres
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: lfs269
      version: '*'
  interval: 1m0s
  targetNamespace: instavote
  values:
    service:
      name: db
    settings:
      authMethod: trust

