apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- db-dev-helmrelease.yaml
- db-staging-helmrelease.yaml
- flux-system-alert.yml
- github-instavote-provider.yml
- helmrepo.yml
- instavote-gitrepository.yaml
- instavote-result-image-update.yaml
- instavote-vote-image-update.yml
- monitoring-kustomization.yml
- monitoring.yml
- redis-dev-alert.yml
- redis-kustomization.yaml
- redis-stg-alert.yml
- redis-stg-kustomization.yaml
- result-image-policy.yml
- results-dev-alert.yml
- results-dev-kustomization.yml
- results-image-repo.yml
- results-stg-alert.yml
- results-stg-kustomization.yml
- slack-notif.yml
- slack.yml
- vote-dev-alert.yml
- vote-dev-kustomaize.yml
- vote-image-policy.yml
- vote-image-repo.yml
- vote-staging-alert.yml
- vote-stg-kustomaize.yml
- worker-dev-alert.yml
- worker-dev.yml
- worker-stg-alert.yml
- worker-stg.yml
