apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: redis-stg
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: redis
    namespace: stginstavote
  interval: 1m0s
  path: ./deploy/redis/stg
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote
  targetNamespace: stginstavote
  timeout: 2m0s

