---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: results-dev
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: results
    namespace: instavote
  interval: 1m0s
  path: ./kustomize/results/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote
  targetNamespace: instavote
  timeout: 2m0s

