---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: worker-stg
  namespace: flux-system
spec:
  dependsOn:
  - name: redis-stg
  healthChecks:
  - kind: Deployment
    name: worker
    namespace: stginstavote
  interval: 1m0s
  path: ./deploy/worker/stg
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote
  targetNamespace: stginstavote
  timeout: 2m0s

